### ISSUE TITLE
Unable to mark tasks as complete

### ISSUE THREAD

**Issue by bethanyios** [fac18/week2-BDIM-fiasco#32]
Attempting to get the mark button to put a strike/opacity through the task so that it is recorded as complete - having difficulties fixing this, tbc...

**Comment by redahaq** [comment]
Could we use a listener and then something like the below maybe? Where we can then set the CSS for strike as 'text-decoration: line-through'. 

```
if (todo.done == true) {
  todoNode.classList.add("strikethrough")
  } else {
  todoNode.classList.remove("strikethrough")
};
```
