### ISSUE TITLE
Unable to style the todo text

### ISSUE THREAD

**Issue by redahaq** [fac18/week2-BDIM-fiasco#36]
I think the font size of the todos should be larger in desktop view.

Using the class '.todo-list__item' seems to only alter the font size of the tick and 'x' (text content of the buttons). 

Oddly, I *am* able to change the font color etc. So it doesn't seem to be a problem with the class name itself.

HALP?!

**Comment by plasticneuron** [comment]
Ok so I think the solution here is to use the `.todo-list__description` class that we have associated with the <span> containing the text for each list item.

**Comment by redahaq** [comment]
Thank you DOM wizard man!
