### ISSUE TITLE
ES6 variable scoping. Warning: long read

### ISSUE THREAD

**Issue by crianonim** [fac18/week2-BDIM-fiasco#41]
I am really glad you are embracing ES6, and in this Issue I want to focus on how you manage scope of the variables in the project. I did a little search and found that you have 68 var declarations, 44 let and 0 const.
I am aware that you are using code that was written for you, so you maybe wanted to be consistent with ES5 code you were given. Fair play. Having said that, from now on, LET's all start CONSTantly use ES6 scoping.

TL;DR: use `const` as a default, `let` if you are sure you need the functionality, and `var`, well, never.

CONST means you cannot reasign any other value to that identifier. You might think that you change values of variables all the time, so maybe `let` should be the default. Wrong, surprisingly variables like to stay the same during their lifecycle.

Let's look at your test code:
https://github.com/fac18/week2-BDIM-fiasco/blob/e1df7719ea73b6a05657b72bf87d91d6b13c7908/test.js#L51-L62

All of the lets and vars there could be replaced by `const`, none of the variables are ever reassigned. It might not seem like a big deal but when I read other people's code (and that's most what you do as a developer) and I see `let` I think 'ok, reassignment on the way, watch out for that one!' and it's an extra effort and if I can't see reassignment I think I missed something. Waste of energy.

I know it's more of a lecture then an issue, but I hope it's helpful. If you found it helpful, maybe share with others my ramblings, or your conclusions from them?

This is an important topic, there are plenty of articles explaining it better:
https://medium.com/javascript-scene/javascript-es6-var-let-or-const-ba58b8dcde75

**Comment by bethanyios** [comment]
I knew the differences and of course the importance of consistency but this is really helpful way of understanding it all fully, thank you :)

**Comment by redahaq** [comment]
Thanks Jan!

"...from now on, LET's all start CONSTantly use ES6 scoping." - @crianonim 

FAVOURITE ISSUE EVER.  👏 👏 👏 👏 👏This is so well explained, not just how but *WHY* let and const are so much better than var in terms of implicit cues about what to expect.

**Comment by crianonim** [comment]
I'm glad you found it useful. Let's just neVAR, eVAR use VAR :stuck_out_tongue_winking_eye:
