### ISSUE TITLE
Git workflow

### ISSUE THREAD

**Issue by crianonim** [fac18/week2-BDIM-fiasco#43]
Nice balance of commits.
You were using co-authoring thing, something we learned after the last project, that is super cool.
I'm just going to pick on one thing: #38 This commit and PR does a lot in one go. I appreciate you actually wrote what that commit does but maybe it would be easier to understand if it consited of separate commits. When you finished working on the branch and did few distinct changes it might be worth add them separately and commit.
So instead of `git add .` and then commit, maybe
`git add index.html` -> commit, then:
`git add test.js` -> commit, etc.

But overall I think your flow is great, keep on!

**Comment by redahaq** [comment]
Thank you, this is an excellent point. We'd certainly aimed to be more granular in our commits this week but some of us (me!!!) forgot almost immediately... 

Also, this suggestion of staging files individually is fab.

**Comment by plasticneuron** [comment]
Thanks Jan, so used to hitting `git add .` that it similarly hadn't occurred to me to stage different files for more granular commits - which I am totally on board with!
