### ISSUE TITLE
Css import

### ISSUE THREAD

**Issue by crianonim** [fac18/week2-BDIM-fiasco#45]
https://github.com/fac18/week2-BDIM-fiasco/blob/e1df7719ea73b6a05657b72bf87d91d6b13c7908/index.html#L13-L15

Interesting approach, what are your reasons to use this as opposed to just directly linking it like other css?
Not saying it's wrong, I'm really curious as I've not seen that before.

**Comment by pat-cki** [comment]
Both methods are compliant standards. 

Using <link> method is probably more elegant as you can limit the amount of your code. Also it seems to be more popular right now than using import. On the other hand import method works well when working on very big projects, when you have to use/import different external css files in your project.
