### ISSUE TITLE
marktodobutton in the dom

### ISSUE THREAD

**Issue by rosalie-baxter** [fac18/week2-BDIM-fiasco#53]
had a play around and i think this would work - just an if/else statement testing the boolean 

let descNode = document.createElement("span");
    descNode.textContent = todo.description;
    todoNode.appendChild(descNode);

      // add markTodo button
      var markTodoButton = document.createElement("button");
      markTodoButton.textContent = '✓';
      markTodoButton.setAttribute("class", "mark-button");
      
      if (todo.done == false) {
        markTodoButton.setAttribute("style", "background-color: #003366;");
        todoNode.setAttribute('style', 'opacity: 1;');
      }
      if (todo.done == true) {
        markTodoButton.contentText = ":heavy_check_mark:";
        markTodoButton.setAttribute("style", "background-color: green;");
        descNode.setAttribute('style', 'opacity: 0.5;');
        descNode.setAttribute("style", "text-decoration: line-through;")
      }
      
      markTodoButton.addEventListener("click", function(event) {
        var newState = todoFunctions.markTodo(state, todo.id);
        update(newState);
      });
      todoNode.appendChild(markTodoButton);

**Comment by bethanyios** [comment]
oooo thank you so much! Will try this asap 

We were so exhausted, on our last legs, and could not work it out for the life of us ha
