### ISSUE TITLE
Using enter key to submit a to-do

### ISSUE THREAD

**Issue by marialani** [fac18/week2-BDIM-fiasco#54]
There is no visual indication that a to-do can be submitted using the enter button as well as the add button

**Comment by redahaq** [comment]
I'm not sure I agree this is required; hitting enter is a pretty intuitive as a 'submit' action. Did you mean for a11y purposes, the button doesn't have an aria-label explaining what it does? As I totally agree with this and we hope to add aria-labels to mark and del buttons using the DOM.
