### ISSUE TITLE
Floating footer

### ISSUE THREAD

**Issue by rosalie-baxter** [fac18/week2-BDIM-fiasco#55]
on certain screen resizes the footer jumps up and all the todos go below it. I think this is bc you've set the position: absolute on the footer but then you also need to set position: relative on the body as its container element - this seemed to work when i tried it!

![Screenshot from 2019-11-08 10-54-18](https://user-images.githubusercontent.com/45801475/68471455-261a1100-0216-11ea-9575-b32608326041.png)

![Screenshot from 2019-11-08 10-55-03](https://user-images.githubusercontent.com/45801475/68471493-421db280-0216-11ea-8cae-82a00cd290d1.png)

**Comment by redahaq** [comment]
Thank you! Great spot.
