### ISSUE TITLE
To Do input stretches on responsive

### ISSUE THREAD

**Issue by rosalie-baxter** [fac18/week2-BDIM-fiasco#57]
might want to give it a smaller max-width potentially? sorry no time to work out if this is the best solution :--- )

![Screenshot from 2019-11-08 11-10-42](https://user-images.githubusercontent.com/45801475/68472529-9f1a6800-0218-11ea-8039-2544d19f9451.png)

**Comment by redahaq** [comment]
Oh, we did this on purpose! *LOL*
